---
- name: configure bastion servers
  hosts: all
  become: yes
  become_user: root  
  roles:
     - users
     - patching
     - packages
     - docker
     - docker-compose
     - awscli
     - terraform
     - helm
     - kubens_kubectl

     - reboot
     